import type { RunPreflightResult } from '../types';
import { issueClass } from '../utils/formatters';
import { Badge } from './StatusView';

export function PreflightChecklist({ preflight }: { preflight: RunPreflightResult | null }) {
  if (!preflight) return <div className='card p-5 text-sm text-slate-300'>Run preflight to evaluate target allowlist, chain validity, path and method scope, rate limits, and required confirmations.</div>;
  const issues = [...preflight.issues, ...preflight.targetValidation.issues, ...preflight.chainValidation.issues];
  return <div className='card p-5'><div className='flex flex-wrap items-center gap-3'><Badge className={preflight.allowed ? 'border-emerald-400/20 bg-emerald-500/15 text-emerald-200' : 'border-rose-400/20 bg-rose-500/15 text-rose-200'}>{preflight.allowed ? 'Preflight allowed' : 'Preflight blocked'}</Badge><Badge className='border-sky-400/20 bg-sky-500/15 text-sky-200'>Effective rate: {preflight.effectiveRateLimit} rps</Badge>{preflight.confirmationRequired && <Badge className='border-amber-400/20 bg-amber-500/15 text-amber-200'>Confirmation required</Badge>}</div><div className='mt-4 grid gap-3 md:grid-cols-3'><div className='rounded-xl border border-white/10 bg-white/5 p-3'><div className='text-xs uppercase text-slate-400'>Target validation</div><div className='mt-1 font-semibold text-white'>{preflight.targetValidation.allowed ? 'Allowed' : 'Blocked'}</div><div className='mt-1 text-xs text-slate-400'>{preflight.targetValidation.resolvedIps.join(', ') || 'No resolved IPs returned'}</div></div><div className='rounded-xl border border-white/10 bg-white/5 p-3'><div className='text-xs uppercase text-slate-400'>Chain validation</div><div className='mt-1 font-semibold text-white'>{preflight.chainValidation.valid ? 'Valid' : 'Invalid'}</div></div><div className='rounded-xl border border-white/10 bg-white/5 p-3'><div className='text-xs uppercase text-slate-400'>Public override</div><div className='mt-1 font-semibold text-white'>{preflight.targetValidation.requiresExplicitPublicOverride ? 'Required' : 'Not required'}</div></div></div><div className='mt-4 space-y-2'>{issues.length === 0 ? <p className='text-sm text-slate-300'>No issues returned by backend preflight.</p> : issues.map((issue) => <div key={`${issue.code}-${issue.message}`} className={`rounded-xl border p-3 text-sm ${issueClass(issue.severity)}`}>{issue.message}</div>)}</div></div>;
}
